### ISSUE TITLE
As a user I can view all details of a specific bid

### ISSUE THREAD

**Issue by jjamay** [ProjectTwentyFive/task-sourcing#47] opened 2017-03-24 08:56 UTC
Including the user who submitted the bid, not just their id

**Comment by JoshuaChing** [comment] 2017-03-24 19:12
we shouldn't even show their id, just need to show their name

**Comment by JoshuaChing** [comment] 2017-03-24 19:14
closing because duplicate of https://github.com/ProjectTwentyFive/task-sourcing/issues/25

**Closed as completed by JoshuaChing** 2017-03-24 19:14 UTC
